### ISSUE TITLE
Support Incremental Updates via MSSQL Change Tracking

### ISSUE THREAD

**Issue by swiffer** [cmoresid/tap-mssql#3]
great to see efforts developing an open source tap for mssql!

the postgres-tag supports different sync_strategies (full_table, incremental, logical_replication).
is support for different strategies considered here as well?
- https://github.com/singer-io/tap-postgres

any plans utilizing enhanced functionality built into mssql (e.g. change tracking)?
- https://www.youtube.com/watch?v=47Ef-ej9Jy8

**Comment by cmoresid** [comment]
Hi! Sorry for the incredibly late reply. I didn't see this issue!

 I'm planning on implementing the following strategies:

* Full table sync
* Incremental sync using a replication key
* Change tracking

Hoping to dedicate some time towards implementing these strategies in the coming weeks.

**Comment by swiffer** [comment]
@cmoresid no worries! Sounds nice! Feel free to Ping me in Case of any testing / Help needed. Sadly No Python coding experience yet...
